[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
]
exceptions = [
    { allow = [
        "Unicode-DFS-2016",
    ], name = "unicode-ident" },
    { allow = [
        "MPL-2.0",
    ], name = "option-ext" },
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
deny = [
    { name = "openssl" },
    { name = "openssl-sys" },
    { name = "libssh2-sys" },

    # No reason to use these
    { name = "cmake" },
    { name = "windows" },
]
skip = [
    { name = "miniz_oxide" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"